#!/bin/bash
# TmuxPilot - A simple tmux session manager
# Author: Ehabw57

# Function to switch or attach to a tmux session
jump_to_session() {
	if [ -n "$TMUX" ]; then
		tmux switch-client -t "$SELECTED_SESSION"
	else
		tmux attach -t "$SELECTED_SESSION"
	fi
}

# Function to create a new tmux session
create_new_session() {
	SESSION_NAME=$(basename "$SELECTED_SESSION")

	if [ -n "$TMUX" ]; then
		tmux new -c "$SELECTED_SESSION" -s "$SESSION_NAME" -d >> /dev/null
		tmux switch-client -t "$SESSION_NAME"
	else
		tmux new -c "$SELECTED_SESSION" -s "$SESSION_NAME" -A 
	fi
}

# Function to check if a tmux server is running
is_tmux_running() {
	tmux list-sessions &> /dev/null
}

case "$1" in
	new)
		SELECTED_SESSION=$(find ~/.config ~/Repos -maxdepth 2 -type d -o -type l | grep -v -e "Code" -e "chromium" -e "discord" -e "git" -e "GIMP" -e "microsoft" | fzf)
		if [ -n "$SELECTED_SESSION" ]; then
			create_new_session
		else
			echo "No distanation selected."
			exit 1
		fi
		;;
	list)
		if is_tmux_running; then
			SELECTED_SESSION=$(tmux list-sessions -F "#{session_name}" | fzf)
			if [ -n "$SELECTED_SESSION" ]; then
				jump_to_session
			else
				echo "No session selected."
				exit 1
			fi
		else
			echo "No tmux server running."
		fi
		;;
esac


