#!/bin/bash
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom &
pgrep -x polybar || "$HOME"/.config/polybar/launch.sh

bspc monitor -d 1 2 3 4 5 6

bspc config border_width         2
bspc config window_gap          12
bspc config top_padding 30

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Thunar state=floating
bspc rule -a Screenkey manage=off
setxkbmap -layout us,ara -option grp:win_space_toggle 
setxkbmap -option caps:escape
"$HOME"/set_live.sh
