#!/bin/bash

# Startups
pgrep -x sxhkd > /dev/null || sxhkd &
#pgrep -x picom > /dev/null || picom &
pgrep -x xsettingsd > /dev/null || xsettingsd &
pgrep -x polybar > /dev/null || "$HOME"/.config/polybar/launch.sh
source "$HOME/.config/bspwm/colorsrc"
bspc config border_width         1
bspc config window_gap          0
bspc config top_padding 24
xrandr --output DP-2 --mode 1920x1080 --primary --output VGA-1 --mode 1024x768 --rotate right --right-of DP-2
bspc monitor DP-2 -d 1 2 3 4 5
bspc monitor VGA-1 -d 6

bspc rule -a '*:*:Scratchpad' state=floating sticky=on rectangle=1300x600+320+220
bspc config split_ratio          0.5

bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

# window rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Thunar state=floating
bspc rule -a feh state=floating
bspc rule -a Nsxiv state=floating
feh --bg-fill ~/.cache/wallpaper.jpg
