#!/bin/bash

# Startups
setxkbmap -layout us,ara -option grp:win_space_toggle 
setxkbmap -option caps:escape
pgrep -x sxhkd > /dev/null || sxhkd &
#pgrep -x picom > /dev/null || picom &
pgrep -x polybar > /dev/null || "$HOME"/.config/polybar/launch.sh
#pgrep -x xwinwrap > /dev/null || "$HOME"/set_live.sh

# Configs
bspc monitor -d 1 2 3 4 5 6
source "$HOME/.config/bspwm/colorsrc"
bspc config border_width         1
bspc config window_gap          10
bspc config top_padding 27


bspc rule -a '*:*:Scratchpad' state=floating sticky=on rectangle=1300x600+320+220
bspc config split_ratio          0.5

bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

# window rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^2'
bspc rule -a Thunar state=floating
