[font]
normal = { family = "DejaVu Sans Mono", style = "Regular" }
bold = { family = "DejaVu Sans Mono", style = "Bold" }
italic = { family = "DejaVu Sans Mono", style = "Italic" }
size = 11.0

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 2

[terminal.shell]
program = "/usr/bin/bash"

[window]
opacity = 0.95

[window.padding]
x = 16
y = 18

[keyboard]
bindings = [
{ key = "H", mods = "Control", action = "ToggleViMode"},
{ key = "P", mods = "Control", action = "Paste"},
]

[general]
live_config_reload = true
import = ['~/.config/alacritty/colors.toml']

[terminal]
