[colors.primary]
background = '#32302f'
foreground = '#d5c4a1'

[colors.cursor]
text = '#504945'
cursor = '#8ec07c'

[colors.normal]
black = '#32302f'
red = '#fb4934'
green = '#b8bb26'
yellow = '#fabd2f'
blue = '#83a598'
magenta = '#d3869b'
cyan = '#8ec07c'
white = '#d5c4a1'

[colors.bright]
black = '#504945'
red = '#fe8019'
green = '#3c3836'
yellow = '#504945'
blue = '#bdae93'
magenta = '#ebdbb2'
cyan = '#d65d0e'
white = '#fbf1c7'